apiVersion: v1
kind: Service
metadata:
  name: postgres-srv
spec:
  clusterIP: None
  selector:
    app: postgres-sfs
  ports:
  - port: 5432
    targetPort: 5432


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-sfs
spec:
  selector:
    matchLabels:
      app: postgres-sfs
  serviceName: postgres-srv
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres-sfs
    spec:
      containers:
      - name: postgres-sfs
        image: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
          name: postgres-port
        env:
          - name: POSTGRES_PASSWORD
            value: asdf
          - name: POSTGRES_USER
            value: werewolf
          - name: POSTGRES_DB
            value: posts
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 128Mi
